using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using MathNet.Numerics.LinearAlgebra.Double;

namespace ManifoldRing
{
    /// <summary>
    /// This puts the responsibility for scalar field multiplication in the manifold class.
    /// We may regard this as the specification of a scalar field handling class.
    /// </summary>
    public abstract class Manifold
    {
        /// <summary>
        /// constructor
        /// </summary>
        /// <param name="dim">manifold dimension</param>
        public Manifold(int dim)
        {
            Id = safeId++;
            Dim = dim;
        }

        /// <summary>
        /// manifold dimension
        /// </summary>
        public int Dim { get; private set; }
        /// <summary>
        /// unique id; serves as key
        /// </summary>
        public int Id { get; set; }
        private static int safeId = 0;
        /// <summary>
        /// the size of the generated underlying array
        /// </summary>
        public int ArraySize { get; set; }

        protected const double E_BOUNDARY_THICKNESS = 0.001;

        /// <summary>
        /// manifold extent
        /// </summary>
        /// <param name="i">direction index</param>
        /// <returns>extent as double</returns>
        public abstract double Extent(int i);
        /// <summary>
        /// manifold stepsize
        /// </summary>
        /// <returns>stepsize as double</returns>
        public abstract double StepSize();
        /// <summary>
        /// nodes per side
        /// </summary>
        /// <param name="i">direction index</param>
        /// <returns>number of nodes as int</returns>
        public abstract int NodesPerSide(int i);
        /// <summary>
        /// initialize manifold members
        /// </summary>
        /// <param name="data">data array</param>
        public abstract void Initialize(double[] data);
        /// <summary>
        /// value at position, delegates to scalar field and interpolates if needed
        /// </summary>
        /// <param name="x">position</param>
        /// <param name="sf">underlying scalar field</param>
        /// <returns>value as double</returns>
        public abstract double Value(double[] x, ScalarField sf);
        /// <summary>
        /// calculate and return the mean concentration in this scalar field
        /// </summary>
        /// <param name="sf">scalar field generated by this manifold</param>
        /// <returns>the mean value</returns>
        public abstract double MeanValue(ScalarField sf);
        /// <summary>
        /// checks if a point in local coordinates is on the manifold
        /// </summary>
        /// <param name="x">the point, assume to be in local coordinates</param>
        /// <returns>true if the point is on the manifold</returns>
        protected abstract bool localIsOn(double[] x);

        // operators

        /// <summary>
        /// scalarfield multiplication
        /// </summary>
        /// <param name="sf1">lh operand</param>
        /// <param name="sf2">rh operand</param>
        /// <returns>resulting field</returns>
        public abstract ScalarField Multiply(ScalarField sf1, ScalarField sf2);
        /// <summary>
        /// addition of a constant to a scalar field
        /// </summary>
        /// <param name="sf">scalar field</param>
        /// <param name="d">constant</param>
        /// <returns></returns>
        public abstract ScalarField Add(ScalarField sf, double d);
        /// <summary>
        /// Laplacian field
        /// </summary>
        /// <param name="sf">field operand</param>
        /// <returns>resulting field</returns>
        public abstract ScalarField Laplacian(ScalarField sf);
        /// <summary>
        /// gradient
        /// </summary>
        /// <param name="x">local position</param>
        /// <param name="sf">field operand</param>
        /// <returns>gradient vector</returns>
        public abstract double[] Grad(double[] x, ScalarField sf);

        /// <summary>
        /// field diffusion, flux term
        /// </summary>
        /// <param name="flux">flux involved</param>
        /// <returns>diffusion flux term as field</returns>
        public abstract ScalarField DiffusionFluxTerm(ScalarField flux, Transform t, ScalarField dst, double dt);
        /// <summary>
        /// integrate over the whole field
        /// </summary>
        /// <param name="sf">field parameter</param>
        /// <returns>integral value</returns>
        public abstract double Integrate(ScalarField sf);
        /// <summary>
        /// manifold length
        /// </summary>
        /// <returns>length as double</returns>
        public abstract double Length();
        /// <summary>
        /// manifold area
        /// </summary>
        /// <returns>area as double</returns>
        public abstract double Area();
        /// <summary>
        /// manifold volume
        /// </summary>
        /// <returns>volume as double</returns>
        public abstract double Volume();
        /// <summary>
        /// manifold voxel volume
        /// </summary>
        /// <returns>voxel volume as double</returns>
        public abstract double VoxelVolume();
        /// <summary>
        /// Restriction of a scalar field to a boundary manifold
        /// </summary>
        /// <param name="from">Scalar field being restricted</param>
        /// <param name="to">Scalar field in restricted space</param>
        /// <returns></returns>
        public abstract ScalarField Restrict(ScalarField from, Transform t, ScalarField to);
        /// <summary>
        /// The points on a manifold that are used to exchange flux
        /// </summary>
        public Vector[] PrincipalPoints { get; set; }
        /// <summary>
        /// Impose Dirichlet boundary conditions
        /// </summary>
        /// <param name="from">Field specified on the boundary manifold</param>
        /// <param name="t">Transform that specifies the geometric relationship between 
        /// the boundary and interior manifolds </param>
        /// <param name="to">Field specified on the interior manifold</param>
        /// <returns>The field after imposing Dirichlet boundary conditions</returns>
        public abstract ScalarField DirichletBC(ScalarField from, Transform t, ScalarField to);
    }

    /// <summary>
    /// base for the ME manifolds
    /// </summary>
    public abstract class MomentExpansionManifold : Manifold
    {
        /// <summary>
        /// constructor
        /// </summary>
        /// <param name="dim">dimension</param>
        public MomentExpansionManifold(int dim) : base(dim)
        {
            ArraySize = 4;
            PrincipalPoints = new Vector[1];
            PrincipalPoints[0] = new DenseVector(3);
        }

        /// <summary>
        /// ME scalarfield multiplication
        /// </summary>
        /// <param name="sf1">lh operand</param>
        /// <param name="sf2">rh operand</param>
        /// <returns>resulting field</returns>
        public override ScalarField Multiply(ScalarField sf1, ScalarField sf2)
        {

            double s1 = sf1.array[0];
            double s2 = sf2.array[0];
            sf1.array[0] *= sf2.array[0];
            for (int i = 1; i < sf1.array.Length; i++)
            {
                sf1.array[i] = sf1.array[i] * s2 + s1 * sf2.array[i];
            }
            return sf1;
        }

        /// <summary>
        /// addition of a constant to a ME scalar field
        /// gradient is not changed
        /// </summary>
        /// <param name="sf">ME scalar field</param>
        /// <param name="d">constant</param>
        /// <returns></returns>
        public override ScalarField Add(ScalarField sf, double d)
        {
            sf.array[0] += d;
            return sf;
        }
            
        /// <summary>
        /// Restriction of a scalar field to an ME boundary manifold
        /// </summary>
        /// <param name="from">scalar field as represented on from.M, the interior manifold</param>
        /// <param name="pos">scalar field as represented on to.M, the boundary manifold</param>
        /// <param name="to">the location of the boundary manifold in the interior manifold</param>
        /// <returns></returns>
        public override ScalarField Restrict(ScalarField from, Transform t, ScalarField to)
        {
            //double[] pos = t.Translation.ToArray();
            double[] pos = t.Position;
            double[] grad = from.M.Grad(pos, from);

            to.array[0] = from.Value(pos);
            to.array[1] = grad[0];
            to.array[2] = grad[1];
            to.array[3] = grad[2];

            return to;
        }

        public override ScalarField DirichletBC(ScalarField from, Transform t, ScalarField to)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// calculate and return the mean concentration in this scalar field
        /// </summary>
        /// <param name="sf">scalar field generated by this manifold</param>
        /// <returns>the mean value</returns>
        public override double MeanValue(ScalarField sf)
        {
            return sf.array[0];
        }
    }

    /// <summary>
    /// tiny sphere manifold
    /// </summary>
    public class TinySphere : MomentExpansionManifold
    {
        private double radius;
        protected ScalarField laplacian;

        /// <summary>
        /// constructor
        /// </summary>
        public TinySphere()
            : base(2)
        {
            laplacian = new ScalarField(this);
        }

        /// <summary>
        /// initialize the radius
        /// </summary>
        /// <param name="data">one element array with the radius</param>
        public override void Initialize(double[] data)
        {
            if (data.Length != 1)
            {
                throw new Exception("TinySphere Initialize data must have length 1");
            }

            radius = data[0];
        }

        /// <summary>
        /// TinySphere manifold extent
        /// </summary>
        /// <param name="i">direction index</param>
        /// <returns>extent as double</returns>
        public override double Extent(int i)
        {
            if (i < 0 || i > 0)
            {
                throw new Exception("Extent out of range.");
            }

            return radius;
        }

        /// <summary>
        /// TinySphere manifold stepsize
        /// </summary>
        /// <returns>stepsize as double</returns>
        public override double StepSize()
        {
            return 0;
        }

        /// <summary>
        /// TinySphere nodes per side
        /// </summary>
        /// <param name="i">direction index</param>
        /// <returns>number of nodes as int</returns>
        public override int NodesPerSide(int i)
        {
            return 0;
        }

        /// <summary>
        /// TinySphere manifold length
        /// </summary>
        /// <returns></returns>
        public override double Length()
        {
            return 0;
        }

        /// <summary>
        /// TinySphere manifold area
        /// </summary>
        /// <returns>area as double</returns>
        public override double Area()
        {
            return 4 * Math.PI * radius * radius;
        }

        /// <summary>
        /// TinySphere manifold volume
        /// </summary>
        /// <returns>volume as double</returns>
        public override double Volume()
        {
            return 0;
        }

        /// <summary>
        /// TinySphere manifold voxel volume
        /// </summary>
        /// <returns>voxel volume as double</returns>
        public override double VoxelVolume()
        {
            return 0;
        }

        /// <summary>
        /// TinySphere value at position, delegates to scalar field
        /// </summary>
        /// <param name="x">position</param>
        /// <param name="sf">underlying scalar field</param>
        /// <returns>value as double</returns>
        public override double Value(double[] x, ScalarField sf)
        {
            double value = sf.array[0],
                   norm = 0;

            for (int i = 0; i < 3; i++)
            {
                norm += x[i] * x[i];
            }
            // returns the mean value only for positions very close to the center of the sphere
            if (norm < 1e-6)
            {
                return value;
            }

            norm = 1.0 / Math.Sqrt(norm);
            for (int i = 1; i < 4; i++)
            {
                value += radius * norm * x[i - 1] * sf.array[i];
            }

            return value;
        }

        /// <summary>
        /// checks if a point in local coordinates is on the manifold
        /// </summary>
        /// <param name="x">the point, assume to be in local coordinates</param>
        /// <returns>true if the point is on the manifold</returns>
        protected override bool localIsOn(double[] x)
        {
            double length = Math.Sqrt(x[0] * x[0] + x[1] * x[1] + x[2] * x[2]);

            return Math.Abs(length - radius) <= E_BOUNDARY_THICKNESS / 2.0;
        }

        /// <summary>
        /// TinySphere Laplacian field
        /// </summary>
        /// <param name="sf">field operand</param>
        /// <returns>resulting field</returns>
        public override ScalarField Laplacian(ScalarField sf)
        {
            var array = laplacian.array;
            array[0] = 0;
            array[1] = sf.array[1];
            array[2] = sf.array[2];
            array[3] = sf.array[3];
            return laplacian.Multiply(-2.0 / (radius * radius));
        }

        /// <summary>
        /// TinySphere gradient
        /// </summary>
        /// <param name="x">local position</param>
        /// <param name="sf">field operand</param>
        /// <returns>gradient vector</returns>
        public override double[] Grad(double[] x, ScalarField sf)
        {
            Vector u = new DenseVector(x);

            u = (DenseVector)u.Normalize(2.0);

            double d = u[0] * sf.array[1] + u[1] * sf.array[2] + u[2] * sf.array[3];

            return new double[] { sf.array[1] - u[0] * d, sf.array[2] - u[1] * d, sf.array[3] - u[2] * d };
        }

        /// <summary>
        /// TinySphere field diffusion, flux term
        /// </summary>
        /// <param name="flux">flux involved</param>
        /// <returns>diffusion flux term as field</returns>
        public override ScalarField DiffusionFluxTerm(ScalarField flux, Transform t, ScalarField dst, double dt)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// TinySphere integrate over the whole field
        /// </summary>
        /// <param name="sf">field parameter</param>
        /// <returns>integral value</returns>
        public override double Integrate(ScalarField sf)
        {
            return sf.array[0] * 4 * Math.PI * radius * radius;
        }
    }

    /// <summary>
    /// tiny ball manifold
    /// </summary>
    public class TinyBall : MomentExpansionManifold
    {
        private double radius;

        protected ScalarField diffusionField;
        protected ScalarField laplacian;
        protected double[] gradient = new double[3];

        /// <summary>
        /// constructor
        /// </summary>
        public TinyBall()
            : base(3)
        {
            laplacian = new ScalarField(this);
            diffusionField = new ScalarField(this);    
        }

        /// <summary>
        /// initialize the radius
        /// </summary>
        /// <param name="data">one element array with the radius</param>
        public override void Initialize(double[] data)
        {
            if (data.Length != 1)
            {
                throw new Exception("TinyBall Initialize data must have length 1");
            }

            radius = data[0];
        }

        /// <summary>
        /// TinyBall manifold extent
        /// </summary>
        /// <param name="i">direction index</param>
        /// <returns>extent as double</returns>
        public override double Extent(int i)
        {
            if (i < 0 || i > 0)
            {
                throw new Exception("Extent out of range.");
            }

            return radius;
        }

        /// <summary>
        /// TinyBall manifold stepsize
        /// </summary>
        /// <returns>stepsize as double</returns>
        public override double StepSize()
        {
            return 0;
        }

        /// <summary>
        /// TinyBall nodes per side
        /// </summary>
        /// <param name="i">direction index</param>
        /// <returns>number of nodes as int</returns>
        public override int NodesPerSide(int i)
        {
            return 0;
        }

        /// <summary>
        /// TinyBall manifold length
        /// </summary>
        /// <returns></returns>
        public override double Length()
        {
            return 0;
        }

        /// <summary>
        /// TinyBall manifold area
        /// </summary>
        /// <returns>area as double</returns>
        public override double Area()
        {
            return 4 * Math.PI * radius * radius;
        }

        /// <summary>
        /// TinyBall manifold volume
        /// </summary>
        /// <returns>volume as double</returns>
        public override double Volume()
        {
            return 4.0 / 3.0 * Math.PI * radius * radius * radius;
        }

        /// <summary>
        /// TinyBall manifold voxel volume
        /// </summary>
        /// <returns>voxel volume as double</returns>
        public override double VoxelVolume()
        {
            return 0;
        }

        /// <summary>
        /// TinyBall value at position, delegates to scalar field
        /// </summary>
        /// <param name="x">position</param>
        /// <param name="sf">underlying scalar field</param>
        /// <returns>value as double</returns>
        public override double Value(double[] x, ScalarField sf)
        {
            // test for out of bounds
            if (localIsOn(x) == false)
            {
                // Return zero when x is not in the ball.
                return 0;
            }

            double value = sf.array[0];

            for (int i = 1; i < 4; i++)
            {
                value += x[i - 1] * sf.array[i];
            }

            return value;
        }

        /// <summary>
        /// checks if a point in local coordinates is on the manifold
        /// </summary>
        /// <param name="x">the point, assume to be in local coordinates</param>
        /// <returns>true if the point is on the manifold</returns>
        protected override bool localIsOn(double[] x)
        {
            double length = Math.Sqrt(x[0] * x[0] + x[1] * x[1] + x[2] * x[2]);

            return length <= radius;
        }

        /// <summary>
        /// TinyBall Laplacian field
        /// Contributions from boundary terms must be applied separately through flux update.
        /// </summary>
        /// <param name="sf">field operand</param>
        /// <returns>resulting field</returns>
        public override ScalarField Laplacian(ScalarField sf)
        {
            var array = laplacian.array;
            array[0] = 0;
            array[1] = sf.array[1];
            array[2] = sf.array[2];
            array[3] = sf.array[3];
            laplacian.Multiply(-5.0 / (radius * radius));
            return laplacian;
        }

        /// <summary>
        /// TinyBall gradient
        /// </summary>
        /// <param name="x">local position</param>
        /// <param name="sf">field operand</param>
        /// <returns>gradient vector</returns>
        public override double[] Grad(double[] x, ScalarField sf)
        {
            if (localIsOn(x) == false)
            {
                return new double[] { 0, 0, 0 };
            }
            gradient[0] = sf.array[1];
            gradient[1] = sf.array[2];
            gradient[2] = sf.array[3];

            return gradient;
        }

        /// <summary>
        /// TinyBall field diffusion, flux term
        /// The flux scalar field has already been divided by the diffusion coefficient in the boundary reaction Step() method.
        /// </summary>
        /// <param name="flux">flux involved</param>
        /// <param name="t">Transform - not used</param>
        /// <returns>diffusion flux term as field</returns>
        public override ScalarField DiffusionFluxTerm(ScalarField flux, Transform t, ScalarField dst, double dt)
        {
            if (flux.M is TinySphere == false)
            {
                throw new Exception("Manifold mismatch: flux for TinyBall must be on TinySphere.");
            }

            var array = diffusionField.array;
            array[0] = 3 * flux.array[0] / radius;
            array[1] = 5 * flux.array[1] / radius;
            array[2] = 5 * flux.array[2] / radius;
            array[3] = 5 * flux.array[3] / radius;

            return dst.Add(diffusionField.Multiply(-dt));
            //return diffusionField;
        }

        /// <summary>
        /// TinyBall integrate over the whole field
        /// </summary>
        /// <param name="sf">field parameter</param>
        /// <returns>integral value</returns>
        public override double Integrate(ScalarField sf)
        {
            return sf.array[0] * 4 * Math.PI * radius * radius * radius / 3;
        }
    }

    /// <summary>
    /// interpolated lattice base
    /// </summary>
    public abstract class InterpolatedNodes : Manifold
    {
        protected int[] nNodesPerSide;
        protected double stepSize;
        protected double[] extent;
        protected Interpolator interpolator;

        /// <summary>
        /// constructor
        /// </summary>
        /// <param name="dim">dimension</param>
        /// <param name="interpolator">handle to the interpolator instance used</param>
        public InterpolatedNodes(int dim, Interpolator interpolator)
            : base(dim)
        {
            this.interpolator = interpolator;
        }

        /// <summary>
        /// initialize the nodes per side and stepsize members
        /// </summary>
        /// <param name="data">data array with dim + 2 entries</param>
        public override void Initialize(double[] data)
        {
            if (data.Length != Dim + 2)
            {
                throw new Exception("Dimension mismatch in interpolated manifold.");
            }

            nNodesPerSide = new int[data.Length - 2];
            for (int i = 0; i < Dim; i++)
            {
                nNodesPerSide[i] = (int)data[i];
            }
            stepSize = data[data.Length - 2];
            bool toroidal = Convert.ToBoolean(data[data.Length - 1]);
 
            extent = new double[Dim];
            // accumulate array size and compute extents
            ArraySize = 1;
            for (int i = 0; i < Dim; i++)
            {
                ArraySize *= nNodesPerSide[i];
                extent[i] = (nNodesPerSide[i] - 1) * stepSize;
            }

            PrincipalPoints = new Vector[ArraySize];
            for (int i = 0; i < ArraySize; i++)
            {
                //PrincipalPoints[i] = linearIndexToLocal(i);
                PrincipalPoints[i] = new DenseVector(linearIndexToLocal(i));
            }

            // initialize interpolator
            interpolator.Init(this, toroidal);
        }

        /// <summary>
        /// IL manifold extent
        /// </summary>
        /// <param name="i">direction index</param>
        /// <returns>extent as double</returns>
        public override double Extent(int i)
        {
            if (i < 0 || i > extent.Length - 1)
            {
                throw new Exception("Extent out of range.");
            }

            return extent[i];
        }

        /// <summary>
        /// IL manifold stepsize
        /// </summary>
        /// <returns>stepsize as double</returns>
        public override double StepSize()
        {
            return stepSize;
        }

        /// <summary>
        /// IL nodes per side
        /// </summary>
        /// <param name="i">direction index</param>
        /// <returns>number of nodes as int</returns>
        public override int NodesPerSide(int i)
        {
            if (i < 0 || i > nNodesPerSide.Length - 1)
            {
                throw new Exception("NodesPerSide out of range.");
            }

            return nNodesPerSide[i];
        }

        /// <summary>
        /// IL scalarfield multiplication
        /// </summary>
        /// <param name="sf1">lh operand</param>
        /// <param name="sf2">rh operand</param>
        /// <returns>resulting field</returns>
        public override ScalarField Multiply(ScalarField sf1, ScalarField sf2)
        {
            for (int i = 0; i < ArraySize; i++)
            {
                sf1.array[i] *= sf2.array[i];
            }
            return sf1;
        }

        /// <summary>
        /// addition of a constant to interpolated nodes scalar field
        /// </summary>
        /// <param name="sf">interpolated nodes scalar field</param>
        /// <param name="d">constant</param>
        /// <returns></returns>
        public override ScalarField Add(ScalarField sf, double d)
        {
            for (int i = 0; i < ArraySize; i++)
            {
                sf.array[i] += d;
            }
            return sf;
            }


        /// <summary>
        /// local point to multidimensional index
        /// </summary>
        /// <param name="x">local point</param>
        /// <returns>index array</returns>
        public int[] localToIndexArray(Vector x)
        //public int[] localToIndexArray(double[] x)
        {
            int[] tmp = new int[Dim];

            for (int i = 0; i < Dim; i++)
            {
                tmp[i] = (int)(x[i] / stepSize);
            }

            return tmp;
        }

        /// <summary>
        /// multidimensional index to local point
        /// </summary>
        /// <param name="idx">index array</param>
        /// <returns>local point</returns>
        public Vector indexArrayToLocal(int[] idx)
        {
            Vector tmp = new DenseVector(Transform.Dim);

            for (int i = 0; i < Dim; i++)
            {
                tmp[i] = idx[i] * stepSize;
            }

            return tmp;
        }

        /// <summary>
        /// multidimensional index to linear index
        /// </summary>
        /// <param name="idx">multidimensional index</param>
        /// <returns>linear index</returns>
        public int indexArrayToLinearIndex(int[] idx)
        {
            int lin = 0;

            if (idx.Length <= 0 || idx.Length > Dim)
            {
                throw new Exception("Index dimension doesn't match manifold.");
            }

            lin = idx[0];
            if (idx.Length >= 2)
            {
                lin += idx[1] * nNodesPerSide[0];
                if (idx.Length == 3)
                {
                    lin += idx[2] * nNodesPerSide[0] * nNodesPerSide[1];
                }
                else
                {
                    throw new Exception("Manifold and index dimension larger than three.");
                }
            }

            return lin;
        }

        /// <summary>
        /// linear index to multidimensional index
        /// </summary>
        /// <param name="lin">linear index</param>
        /// <returns>multidimensional index</returns>
        public int[] linearIndexToIndexArray(int lin)
        {
            int[] idx = new int[Dim];

            if (Dim >= 1)
            {
                if (Dim >= 2)
                {
                    if (Dim == 3)
                    {
                        idx[2] = lin / (nNodesPerSide[0] * nNodesPerSide[1]);
                        lin %= nNodesPerSide[0] * nNodesPerSide[1];
                    }
                    idx[1] = lin / nNodesPerSide[0];
                    lin %= nNodesPerSide[0];
                }
                idx[0] = lin;
            }

            return idx;
        }

        /// <summary>
        /// linear index to local point
        /// </summary>
        /// <param name="lin">linear index</param>
        /// <returns>local point</returns>
        //public Vector linearIndexToLocal(int lin)
        public double[] linearIndexToLocal(int lin)
        {
            //return indexArrayToLocal(linearIndexToIndexArray(lin));
            return indexArrayToLocal(linearIndexToIndexArray(lin)).ToArray();
        }

        /// <summary>
        /// checks if a point in local coordinates is on the manifold
        /// </summary>
        /// <param name="x">the point, assume to be in local coordinates</param>
        /// <returns>true if the point is on the manifold</returns>
        protected override bool localIsOn(double[] x)
        {
            for (int i = Dim; i < Transform.Dim; i++)
            {
                if (x[i] != 0)
                {
                    return false;
                }
            }
            for (int i = 0; i < Dim; i++)
            {
                if (x[i] < 0 || x[i] > extent[i])
                {
                    return false;
                }
            }
            return true;
        }

        /// <summary>
        /// IL value at position, delegates to scalar field and interpolates
        /// </summary>
        /// <param name="x">position</param>
        /// <param name="sf">underlying scalar field</param>
        /// <returns>value as double</returns>
        public override double Value(double[] x, ScalarField sf)
        {
            // machinery for interpolation
            // test for out of bounds
            if (localIsOn(x) == false)
            {
                // Note: is returning zero the right thing to do when x is out of bounds?
                return 0;
            }
            return interpolator.Interpolate(x, sf);
        }

        /// <summary>
        /// calculate and return the mean concentration in this scalar field
        /// </summary>
        /// <param name="sf">scalar field generated by this manifold</param>
        /// <returns>the mean value</returns>
        public override double MeanValue(ScalarField sf)
        {
            return interpolator.Integration(sf) / (sf.M.Extent(0) * sf.M.Extent(1) * sf.M.Extent(2));
        }

        /// <summary>
        /// IL Laplacian field
        /// </summary>
        /// <param name="sf">field operand</param>
        /// <returns>resulting field</returns>
        public override ScalarField Laplacian(ScalarField sf)
        {
            return interpolator.Laplacian(sf);
        }

        /// <summary>
        /// IL gradient
        /// </summary>
        /// <param name="x">local position</param>
        /// <param name="sf">field operand</param>
        /// <returns>gradient vector</returns>
        public override double[] Grad(double[] x, ScalarField sf)
        {
            if (localIsOn(x) == false)
            {
                return new double[Dim];
            }
            if (double.IsNaN(x[0]))
            {
                int y = 1;
            }
            return interpolator.Gradient(x, sf);
        }


        /// <summary>
        /// Restriction of a scalar field to an IL boundary manifold
        /// </summary>
        /// <param name="from">scalar field as represented on from.M, the interior manifold</param>
        /// <param name="t">Transform that defines spatial relation between from and to</param>
        /// <param name="to">the location of the boundary manifold in the interior manifold</param>
        /// <returns></returns>
        public override ScalarField Restrict(ScalarField from, Transform t, ScalarField to)
        {
            double[] pos = t.Translation.ArrayCopy;
            Vector x = new DenseVector(new double[3]);

            for (int i = 0; i < ArraySize; i++)
            {
                // the coordinates of this interpolation point in this boundary manifold
                //x = this.linearIndexToLocal(i);
                x = new DenseVector(this.linearIndexToLocal(i));
                // x+pos are the coordinates of this interpolation point in the interior manifold
                //to.array[i] = from.M.Value(x + pos, from);                
                Vector y = new DenseVector(pos);
                y = (DenseVector)(x + y);
                to.array[i] = from.M.Value(y.ToArray(), from);
            }
            return to;
        }

        public override ScalarField DiffusionFluxTerm(ScalarField flux, Transform t, ScalarField sf, double dt)
        {
            return interpolator.DiffusionFlux(flux, t, sf, dt);
        }

        /// <summary>
        /// Impose Dirichlet boundary conditions
        /// </summary>
        /// <param name="from">Field specified on the boundary manifold</param>
        /// <param name="t">Transform that specifies the geometric relationship between 
        /// the boundary and interior manifolds </param>
        /// <param name="to">Field specified on the interior manifold</param>
        /// <returns>The field after imposing Dirichlet boundary conditions</returns>
        public override ScalarField DirichletBC(ScalarField from, Transform t, ScalarField to)
        {
            return interpolator.DirichletBC(from, t, to);
        }
    }

    /// <summary>
    /// IL line
    /// </summary>
    public class InterpolatedLine : InterpolatedNodes
    {
        /// <summary>
        /// constructor
        /// </summary>
        /// <param name="interpolator">handle to the interpolator instance used</param>
        public InterpolatedLine(Interpolator interpolator)
            : base(1, interpolator)
        {
        }

        /// <summary>
        /// IL line manifold length
        /// </summary>
        /// <returns></returns>
        public override double Length()
        {
            return extent[0];
        }

        /// <summary>
        /// IL line manifold area
        /// </summary>
        /// <returns>area as double</returns>
        public override double Area()
        {
            return 0;
        }

        /// <summary>
        /// IL line manifold volume
        /// </summary>
        /// <returns>volume as double</returns>
        public override double Volume()
        {
            return 0;
        }

        /// <summary>
        /// IL line manifold voxel volume
        /// </summary>
        /// <returns>voxel volume as double</returns>
        public override double VoxelVolume()
        {
            return 0;
        }

        /// <summary>
        /// IL line integrate over the whole field
        /// </summary>
        /// <param name="sf">field parameter</param>
        /// <returns>integral value</returns>
        public override double Integrate(ScalarField sf)
        {
            double[] point = new double[] { 0, 0, 0 };
            double sum = 0,
                   voxel = stepSize;

                for (int i = 0; i < nNodesPerSide[0] - 1; i++)
                {
                    point[0] = (i + 0.5) * stepSize;

                    // The value at the center of the voxel
                    sum += sf.Value(point);
                }

            return sum * voxel;
        }
    }

    /// <summary>
    /// IL rectangle
    /// </summary>
    public class InterpolatedRectangle : InterpolatedNodes
    {
        /// <summary>
        /// constructor
        /// </summary>
        /// <param name="interpolator">handle to the interpolator instance used</param>
        public InterpolatedRectangle(Interpolator interpolator)
            : base(2, interpolator)
        {
        }

        /// <summary>
        /// IL rectangle manifold length
        /// </summary>
        /// <returns></returns>
        public override double Length()
        {
            return 0;
        }

        /// <summary>
        /// IL rectangle manifold area
        /// </summary>
        /// <returns>area as double</returns>
        public override double Area()
        {
            return extent[0] * extent[1];
        }

        /// <summary>
        /// IL rectangle manifold volume
        /// </summary>
        /// <returns>volume as double</returns>
        public override double Volume()
        {
            return 0;
        }

        /// <summary>
        /// IL rectangle manifold voxel volume
        /// </summary>
        /// <returns>voxel volume as double</returns>
        public override double VoxelVolume()
        {
            return 0;
        }

        /// <summary>
        /// IL rectangle integrate over the whole field
        /// </summary>
        /// <param name="sf">field parameter</param>
        /// <returns>integral value</returns>
        public override double Integrate(ScalarField sf)
        {
            double[] point = new double[] { 0, 0, 0 };
            double sum = 0,
                   voxel = stepSize * stepSize;

            for (int j = 0; j < nNodesPerSide[1] - 1; j++)
            {
                for (int i = 0; i < nNodesPerSide[0] - 1; i++)
                {
                    point[0] = (i + 0.5) * stepSize;
                    point[1] = (j + 0.5) * stepSize;

                    // The value at the center of the voxel
                    sum += sf.Value(point);
                }
            }

            return sum * voxel;
        }
    }

    /// <summary>
    /// IL prism
    /// </summary>
    public class InterpolatedRectangularPrism : InterpolatedNodes
    {
        /// <summary>
        /// constructor
        /// </summary>
        /// <param name="interpolator">handle to the interpolator instance used</param>
        public InterpolatedRectangularPrism(Interpolator interpolator)
            : base(3, interpolator)
        {
        }

        /// <summary>
        /// IL prism manifold length
        /// </summary>
        /// <returns></returns>
        public override double Length()
        {
            return 0;
        }

        /// <summary>
        /// IL prism manifold area
        /// </summary>
        /// <returns>area as double</returns>
        public override double Area()
        {
            return extent[0] * extent[1] * 2 + extent[1] * extent[2] * 2 + extent[2] * extent[0] * 2;
        }

        /// <summary>
        /// IL prism manifold volume
        /// </summary>
        /// <returns>volume as double</returns>
        public override double Volume()
        {
            return extent[0] * extent[1] * extent[2];
        }

        /// <summary>
        /// IL prism manifold voxel volume
        /// </summary>
        /// <returns>voxel volume as double</returns>
        public override double VoxelVolume()
        {
            return stepSize * stepSize * stepSize;
        }

        /// <summary>
        /// IL prism integrate over the whole field
        /// </summary>
        /// <param name="sf">field parameter</param>
        /// <returns>integral value</returns>
        public override double Integrate(ScalarField sf)
        {
            double[] point = new double[3];
            double sum = 0,
                   voxel = stepSize * stepSize * stepSize;

            for (int k = 0; k < nNodesPerSide[2] - 1; k++)
            {
                for (int j = 0; j < nNodesPerSide[1] - 1; j++)
                {
                    for (int i = 0; i < nNodesPerSide[0] - 1; i++)
                    {
                        point[0] = (i + 0.5) * stepSize;
                        point[1] = (j + 0.5) * stepSize;
                        point[2] = (k + 0.5) * stepSize;

                        // The value at the center of the voxel
                        sum += sf.Value(point);
                    }
                }
            }

            return sum * voxel;
        }
    }

    /// <summary>
    /// A point manifold with no spatial extent.
    /// </summary>
    public class PointManifold : Manifold
    {
        /// <summary>
        /// constructor
        /// </summary>
        /// <param name="dim">manifold dimension</param>
        public PointManifold()
            : base(0)
        {
            ArraySize = 1;
            PrincipalPoints = new DenseVector[1];
            PrincipalPoints[0] = new DenseVector(3);
        }

        /// <summary>
        /// manifold extent
        /// </summary>
        /// <param name="i">direction index</param>
        /// <returns>extent as double</returns>
        public override double Extent(int i)
        {
            return 0;
        }

        /// <summary>
        /// manifold stepsize
        /// </summary>
        /// <returns>stepsize as double</returns>
        public override double StepSize()
        {
            return 0;
        }

        /// <summary>
        /// nodes per side
        /// </summary>
        /// <param name="i">direction index</param>
        /// <returns>number of nodes as int</returns>
        public override int NodesPerSide(int i)
        {
            return 0;
        }

        /// <summary>
        /// initialize manifold members
        /// </summary>
        /// <param name="data">data array</param>
        public override void Initialize(double[] data)
        {
            // no initialization needed
            return;
        }

        /// <summary>
        /// value at position, delegates to scalar field 
        /// </summary>
        /// <param name="x">position</param>
        /// <param name="sf">underlying scalar field</param>
        /// <returns>value as double</returns>
        public override double Value(double[] x, ScalarField sf)
        {
            if (localIsOn(x))
            {
                return sf.array[0];
            }
            else
            {
                return 0;
            }
        }

        /// <summary>
        /// calculate and return the mean concentration in this scalar field
        /// </summary>
        /// <param name="sf">scalar field generated by this manifold</param>
        /// <returns>the mean value</returns>
        public override double MeanValue(ScalarField sf)
        {
            return sf.array[0];
        }

        /// <summary>
        /// checks if a point in local coordinates is on the manifold
        /// a point is on the PointManifold if it is "close enough" to the origin
        /// </summary>
        /// <param name="x">the point, assume to be in local coordinates</param>
        /// <returns>true if the point is on the manifold</returns>
        protected override bool localIsOn(double[] x)
        {
            return Math.Abs(x[0]) <= E_BOUNDARY_THICKNESS / 2.0;
        }

        // operators

        /// <summary>
        /// scalarfield multiplication
        /// </summary>
        /// <param name="sf1">lh operand</param>
        /// <param name="sf2">rh operand</param>
        /// <returns>resulting field</returns>
        public override ScalarField Multiply(ScalarField sf1, ScalarField sf2)
        {
            sf1.array[0] *= sf2.array[0];
            return sf1;
        }

        /// <summary>
        /// addition of a constant to a point manifold
        /// </summary>
        /// <param name="sf">point manifold scalar field</param>
        /// <param name="d">constant</param>
        /// <returns></returns>
        public override ScalarField  Add(ScalarField sf, double d)
        {
            sf.array[0] += d;
            return sf;
        }

        /// <summary>
        /// Laplacian field
        /// </summary>
        /// <param name="sf">field operand</param>
        /// <returns>resulting field</returns>
        public override ScalarField Laplacian(ScalarField sf)
        {
            // return zeros - no diffusion
            return new ScalarField(this);
        }

        /// <summary>
        /// gradient
        /// </summary>
        /// <param name="x">local position</param>
        /// <param name="sf">field operand</param>
        /// <returns>gradient vector</returns>
        public override double[] Grad(double[] x, ScalarField sf)
        {
            return new double[x.Length];
        }

        /// <summary>
        /// field diffusion, flux term
        /// </summary>
        /// <param name="flux">flux involved</param>
        /// <returns>diffusion flux term as field</returns>
        public override ScalarField DiffusionFluxTerm(ScalarField flux, Transform t, ScalarField dst, double dt)
        {
            throw new Exception("DiffusionFluxTerm not implemented for PointManifold fields");
        }

        /// <summary>
        /// integrate over the whole field
        /// </summary>
        /// <param name="sf">field parameter</param>
        /// <returns>integral value</returns>
        public override double Integrate(ScalarField sf)
        {
            return sf.array[0];
        }

        /// <summary>
        /// manifold length
        /// </summary>
        /// <returns></returns>
        public override double Length()
        {
            return 0;
        }

        /// <summary>
        /// manifold area
        /// </summary>
        /// <returns>area as double</returns>
        public override double Area()
        {
            return 0;
        }

        /// <summary>
        /// manifold volume
        /// </summary>
        /// <returns>volume as double</returns>
        public override double Volume()
        {
            return 0;
        }

        /// <summary>
        /// manifold voxel volume
        /// </summary>
        /// <returns>voxel volume as double</returns>
        public override double VoxelVolume()
        {
            return 0;
        }

        /// <summary>
        /// Restriction of a scalar field to the PointManifold
        /// </summary>
        /// <param name="from">Scalar field being restricted</param>
        /// <param name="to">Scalar field in restricted space</param>
        /// <returns></returns>
        public override ScalarField Restrict(ScalarField from, Transform t, ScalarField to)
        {
                double[] pos = t.Translation.ArrayCopy;
                to.array[0] = from.Value(pos);

                return to;
        }

        /// <summary>
        /// Impose Dirichlet boundary conditions
        /// </summary>
        /// <param name="from">Field specified on the boundary manifold</param>
        /// <param name="t">Transform that specifies the geometric relationship between 
        /// the boundary and interior manifolds </param>
        /// <param name="to">Field specified on the interior manifold</param>
        /// <returns>The field after imposing Dirichlet boundary conditions</returns>
        public override ScalarField DirichletBC(ScalarField from, Transform t, ScalarField to)
        {
            throw new Exception("DirichletBC not implemented for PointManifold fields");
        }
    }
}
